### PR TITLE
feat/all: add initial code

### PR DESCRIPTION
**Pull request by Fraser999**
This is the initial implementation.

---

This change is [Reviewable](https://reviewable.io/reviews/maidsafe/libsodium_seeded_prng/1)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 13 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[.travis.yml, line 9 [r1]](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1#-KKNrbKd0N3JQbdi1r7C:-KKNrbKd0N3JQbdi1r7D:879785621) ([raw file](https://github.com/maidsafe/libsodium_seeded_prng/blob/851a1d9202251b7dd13f6d8b698f4c96aff2c736/.travis.yml#L9)):_

> ``` YAML
> language: rust
> rust:
>   - beta
> ```

I think in most crates we only have stable and nightly. Not sure if beta is worth the extra wait on Travis?

---

_[src/xor_shift_random.rs, line 104 [r1]](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1#-KKNvVURgV8nxi3GBHue:-KKNvVUS1EhpIhBHwSh4:1865442458) ([raw file](https://github.com/maidsafe/libsodium_seeded_prng/blob/851a1d9202251b7dd13f6d8b698f4c96aff2c736/src/xor_shift_random.rs#L104)):_

> ``` Rust
>             let ptr = buf as *mut u8;
>             for i in 0..size {
>                 *ptr.offset(i as isize) = super::RNG.with(|rng| rng.borrow_mut().gen());
> ```

Would it be more efficient to borrow the `rng` only once, outside the loop?

---

_[src/xor_shift_random.rs, line 156 [r1]](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1#-KKNxBYdds3RQFrZRk-M:-KKNxBYeNACBPzj1WdJN:-1096376582) ([raw file](https://github.com/maidsafe/libsodium_seeded_prng/blob/851a1d9202251b7dd13f6d8b698f4c96aff2c736/src/xor_shift_random.rs#L156)):_

> ``` Rust
> #[allow(unsafe_code)]
> pub fn init(optional_seed: Option<[u32; 4]>) -> Result<Seed, Error> {
>     let mut init_result = &mut *INIT_RESULT.lock().expect("");
> ```

This would be one of the example where we've kind of agreed to be allowed to use `unwrap`, or rather the `unwrap!` macro. At least I think an `expect` with an empty string doesn't add much value over an `unwrap` ...
(Also below.)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1)_

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/xor_shift_random.rs, line 104 [r1]](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1#-KKNvVURgV8nxi3GBHue:-KKOG30bl6nOlenQ7muP:567587153) ([raw file](https://github.com/maidsafe/libsodium_seeded_prng/blob/851a1d9202251b7dd13f6d8b698f4c96aff2c736/src/xor_shift_random.rs#L104)):_
<details><summary>

<i>Previously, afck (Andreas Fackler) wrote…</i></summary>



> Would it be more efficient to borrow the `rng` only once, outside the loop?
> </details>
> I ran into lifetime issues doing that.  Let me have another look.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1)_

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/xor_shift_random.rs, line 156 [r1]](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1#-KKNxBYdds3RQFrZRk-M:-KKOGrq7L_vL4py5Rkr1:324711739) ([raw file](https://github.com/maidsafe/libsodium_seeded_prng/blob/851a1d9202251b7dd13f6d8b698f4c96aff2c736/src/xor_shift_random.rs#L156)):_
<details><summary>

<i>Previously, afck (Andreas Fackler) wrote…</i></summary>



> This would be one of the example where we've kind of agreed to be allowed to use `unwrap`, or rather the `unwrap!` macro. At least I think an `expect` with an empty string doesn't add much value over an `unwrap` ...
> (Also below.)
> </details>
> Yeah, sorry - I meant to ask about these before committing.  Which choice do you prefer?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1)_

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/xor_shift_random.rs, line 156 [r1]](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1#-KKNxBYdds3RQFrZRk-M:-KKOLiFwmUNalqAfg8IY:-2086691255) ([raw file](https://github.com/maidsafe/libsodium_seeded_prng/blob/851a1d9202251b7dd13f6d8b698f4c96aff2c736/src/xor_shift_random.rs#L156)):_
<details><summary>

<i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>



> Yeah, sorry - I meant to ask about these before committing.  Which choice do you prefer?
> </details>
> As discussed in https://github.com/maidsafe/crust/issues/736, let's use the unwrap crate and the `unwrap!` macro for locking mutexes.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1)_

**Comment by afck** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/xor_shift_random.rs, line 103 [r3]](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1#-KKOTlWSxPbIe3L57L78:-KKOTlWSxPbIe3L57L79:1148238189) ([raw file](https://github.com/maidsafe/libsodium_seeded_prng/blob/8593050fea2537eae07d0204fc79e7b9de3247c7/src/xor_shift_random.rs#L103)):_

> ``` Rust
>         unsafe {
>             let ptr = buf as *mut u8;
>             let rng_ptr = super::RNG.with(|rng| rng.clone());
> ```

But that wouldn't move the original `rng` forward now, so two subsequent calls to `buf` would create the same result, would they?
If that's the case, it's better to revert to borrowing it inside the loop, I think.
Or could the whole loop be moved into the closure passed to `with`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1)_

**Comment by afck** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/libsodium_seeded_prng/1)_

**Pull request merged**
